version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tox
    versions:
    - 3.20.1
    - 3.21.3
  - dependency-name: tqdm
    versions:
    - 4.55.0
    - 4.56.0
  - dependency-name: coverage
    versions:
    - 5.3.1
    - "5.4"
  - dependency-name: sphinx
    versions:
    - 3.4.1
    - 3.4.3
  - dependency-name: watchdog
    versions:
    - 1.0.2
